// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace SpecFlowProject.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class EmployersLibraryFeature : object, Xunit.IClassFixture<EmployersLibraryFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "EmployersLibrary.feature"
#line hidden
        
        public EmployersLibraryFeature(EmployersLibraryFeature.FixtureData fixtureData, SpecFlowProject_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "EmployersLibrary", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 3
#line hidden
#line 4
 testRunner.Given("I create company with name \'FLS\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "LastName",
                        "FirstName",
                        "ID"});
            table1.AddRow(new string[] {
                        "Vlasov",
                        "Alexei",
                        "IdOfPerson1"});
            table1.AddRow(new string[] {
                        "Vlasov",
                        "Andrei",
                        "IdOfPerson2"});
            table1.AddRow(new string[] {
                        "Ivlev",
                        "Andrei",
                        "IdOfPerson3"});
            table1.AddRow(new string[] {
                        "Filipov",
                        "Vladimir",
                        "IdOfPerson4"});
#line 5
 testRunner.And("I add persons to the company with name \'FLS\'", ((string)(null)), table1, "And ");
#line hidden
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="GetStuffOfficeEmployers_WhenAllPersonInOffice")]
        [Xunit.TraitAttribute("FeatureTitle", "EmployersLibrary")]
        [Xunit.TraitAttribute("Description", "GetStuffOfficeEmployers_WhenAllPersonInOffice")]
        [Xunit.TraitAttribute("Category", "Alex")]
        public virtual void GetStuffOfficeEmployers_WhenAllPersonInOffice()
        {
            string[] tagsOfScenario = new string[] {
                    "Alex"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("GetStuffOfficeEmployers_WhenAllPersonInOffice", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 13
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 3
this.FeatureBackground();
#line hidden
#line 14
 testRunner.When("I Get List Of All Company Employers as new Director of company \'FLS\' and put it i" +
                        "n actual scenario context \'allCompanyEmployers\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 15
 testRunner.When("I Get List Of Stuff Office Employers as new Director of company \'FLS\' and put it " +
                        "in expected scenario context \'stuffOfficeEmployers\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 16
 testRunner.Then("I validate count of \'allCompanyEmployers\' collection is \'4\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                            "ID"});
                table2.AddRow(new string[] {
                            "IdOfPerson1"});
                table2.AddRow(new string[] {
                            "IdOfPerson2"});
                table2.AddRow(new string[] {
                            "IdOfPerson3"});
                table2.AddRow(new string[] {
                            "IdOfPerson4"});
#line 17
 testRunner.And("I validate collection of \'allCompanyEmployers\' \'FLS\' company consist of person wi" +
                        "th id", ((string)(null)), table2, "And ");
#line hidden
#line 23
 testRunner.And("I validate count of \'stuffOfficeEmployers\' collection is \'4\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                            "ID"});
                table3.AddRow(new string[] {
                            "IdOfPerson1"});
                table3.AddRow(new string[] {
                            "IdOfPerson2"});
                table3.AddRow(new string[] {
                            "IdOfPerson3"});
                table3.AddRow(new string[] {
                            "IdOfPerson4"});
#line 24
 testRunner.And("I validate collection of \'stuffOfficeEmployers\' \'FLS\' company consist of person w" +
                        "ith id", ((string)(null)), table3, "And ");
#line hidden
#line 30
 testRunner.And("I validate that collection of \'stuffOfficeEmployers\' does not contain absent pers" +
                        "ons", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="GetStuffOfficeEmployers_WhenNobodyPersonInOffice")]
        [Xunit.TraitAttribute("FeatureTitle", "EmployersLibrary")]
        [Xunit.TraitAttribute("Description", "GetStuffOfficeEmployers_WhenNobodyPersonInOffice")]
        [Xunit.TraitAttribute("Category", "Alex")]
        public virtual void GetStuffOfficeEmployers_WhenNobodyPersonInOffice()
        {
            string[] tagsOfScenario = new string[] {
                    "Alex"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("GetStuffOfficeEmployers_WhenNobodyPersonInOffice", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 33
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 3
this.FeatureBackground();
#line hidden
#line 34
 testRunner.When("All person come out from the office company \'FLS\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 35
 testRunner.When("I Get List Of All Company Employers as new Director of company \'FLS\' and put it i" +
                        "n actual scenario context \'allCompanyEmployers\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 36
 testRunner.When("I Get List Of Stuff Office Employers as new Director of company \'FLS\' and put it " +
                        "in expected scenario context \'NobodyOfficeEmployersInOffice\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 37
 testRunner.Then("I validate count of \'allCompanyEmployers\' collection is \'4\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                            "ID"});
                table4.AddRow(new string[] {
                            "IdOfPerson1"});
                table4.AddRow(new string[] {
                            "IdOfPerson2"});
                table4.AddRow(new string[] {
                            "IdOfPerson3"});
                table4.AddRow(new string[] {
                            "IdOfPerson4"});
#line 38
 testRunner.And("I validate collection of \'allCompanyEmployers\' \'FLS\' company consist of person wi" +
                        "th id", ((string)(null)), table4, "And ");
#line hidden
#line 44
 testRunner.And("I validate count of \'NobodyOfficeEmployersInOffice\' collection is \'0\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 45
 testRunner.And("I validate collection \'NobodyOfficeEmployersInOffice\' is empty", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="GetStuffOfficeEmployers_WhenOnePersonComeOut")]
        [Xunit.TraitAttribute("FeatureTitle", "EmployersLibrary")]
        [Xunit.TraitAttribute("Description", "GetStuffOfficeEmployers_WhenOnePersonComeOut")]
        [Xunit.TraitAttribute("Category", "Alex")]
        public virtual void GetStuffOfficeEmployers_WhenOnePersonComeOut()
        {
            string[] tagsOfScenario = new string[] {
                    "Alex"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("GetStuffOfficeEmployers_WhenOnePersonComeOut", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 48
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 3
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                            "ID"});
                table5.AddRow(new string[] {
                            "IdOfPerson3"});
#line 49
 testRunner.When("The person with id come out from the office company \'FLS\'", ((string)(null)), table5, "When ");
#line hidden
#line 52
 testRunner.When("I Get List Of All Company Employers as new Director of company \'FLS\' and put it i" +
                        "n actual scenario context \'allCompanyEmployers\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 53
 testRunner.When("I Get List Of Stuff Office Employers as new Director of company \'FLS\' and put it " +
                        "in expected scenario context \'stuffOfficeEmployers\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 54
 testRunner.Then("I validate count of \'allCompanyEmployers\' collection is \'4\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                            "ID"});
                table6.AddRow(new string[] {
                            "IdOfPerson1"});
                table6.AddRow(new string[] {
                            "IdOfPerson2"});
                table6.AddRow(new string[] {
                            "IdOfPerson3"});
                table6.AddRow(new string[] {
                            "IdOfPerson4"});
#line 55
 testRunner.And("I validate collection of \'allCompanyEmployers\' \'FLS\' company consist of person wi" +
                        "th id", ((string)(null)), table6, "And ");
#line hidden
                TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                            "ID"});
                table7.AddRow(new string[] {
                            "IdOfPerson1"});
                table7.AddRow(new string[] {
                            "IdOfPerson2"});
                table7.AddRow(new string[] {
                            "IdOfPerson4"});
#line 61
 testRunner.And("I validate collection of \'stuffOfficeEmployers\' \'FLS\' company consist of person w" +
                        "ith id", ((string)(null)), table7, "And ");
#line hidden
#line 66
 testRunner.Then("I validate count of \'stuffOfficeEmployers\' collection is \'3\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="GetStuffOfficeEmployers_WhenOnePersonComeOutAndComeIn")]
        [Xunit.TraitAttribute("FeatureTitle", "EmployersLibrary")]
        [Xunit.TraitAttribute("Description", "GetStuffOfficeEmployers_WhenOnePersonComeOutAndComeIn")]
        [Xunit.TraitAttribute("Category", "Alex")]
        public virtual void GetStuffOfficeEmployers_WhenOnePersonComeOutAndComeIn()
        {
            string[] tagsOfScenario = new string[] {
                    "Alex"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("GetStuffOfficeEmployers_WhenOnePersonComeOutAndComeIn", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 69
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 3
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                            "ID"});
                table8.AddRow(new string[] {
                            "IdOfPerson1"});
#line 70
 testRunner.When("The person with id come out from the office company \'FLS\'", ((string)(null)), table8, "When ");
#line hidden
                TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                            "ID"});
                table9.AddRow(new string[] {
                            "IdOfPerson1"});
#line 73
 testRunner.When("The person with id come in to the office company \'FLS\'", ((string)(null)), table9, "When ");
#line hidden
#line 76
 testRunner.When("I Get List Of All Company Employers as new Director of company \'FLS\' and put it i" +
                        "n actual scenario context \'allCompanyEmployers\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 77
 testRunner.When("I Get List Of Stuff Office Employers as new Director of company \'FLS\' and put it " +
                        "in expected scenario context \'stuffOfficeEmployers\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 78
 testRunner.Then("I validate count of \'allCompanyEmployers\' collection is \'4\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                            "ID"});
                table10.AddRow(new string[] {
                            "IdOfPerson1"});
                table10.AddRow(new string[] {
                            "IdOfPerson2"});
                table10.AddRow(new string[] {
                            "IdOfPerson3"});
                table10.AddRow(new string[] {
                            "IdOfPerson4"});
#line 79
 testRunner.And("I validate collection of \'allCompanyEmployers\' \'FLS\' company consist of person wi" +
                        "th id", ((string)(null)), table10, "And ");
#line hidden
                TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                            "ID"});
                table11.AddRow(new string[] {
                            "IdOfPerson1"});
                table11.AddRow(new string[] {
                            "IdOfPerson2"});
                table11.AddRow(new string[] {
                            "IdOfPerson3"});
                table11.AddRow(new string[] {
                            "IdOfPerson4"});
#line 85
 testRunner.And("I validate collection of \'stuffOfficeEmployers\' \'FLS\' company consist of person w" +
                        "ith id", ((string)(null)), table11, "And ");
#line hidden
#line 91
 testRunner.And("I validate count of \'stuffOfficeEmployers\' collection is \'4\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 92
 testRunner.And("I validate that collection of \'stuffOfficeEmployers\' does not contain absent pers" +
                        "ons", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="GetStuffOfficeEmployers_WhenDifferentPersonComeOutAndComeIn")]
        [Xunit.TraitAttribute("FeatureTitle", "EmployersLibrary")]
        [Xunit.TraitAttribute("Description", "GetStuffOfficeEmployers_WhenDifferentPersonComeOutAndComeIn")]
        [Xunit.TraitAttribute("Category", "Alex")]
        public virtual void GetStuffOfficeEmployers_WhenDifferentPersonComeOutAndComeIn()
        {
            string[] tagsOfScenario = new string[] {
                    "Alex"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("GetStuffOfficeEmployers_WhenDifferentPersonComeOutAndComeIn", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 95
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 3
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                            "ID"});
                table12.AddRow(new string[] {
                            "IdOfPerson1"});
                table12.AddRow(new string[] {
                            "IdOfPerson2"});
#line 96
 testRunner.When("The person with id come out from the office company \'FLS\'", ((string)(null)), table12, "When ");
#line hidden
                TechTalk.SpecFlow.Table table13 = new TechTalk.SpecFlow.Table(new string[] {
                            "ID"});
                table13.AddRow(new string[] {
                            "IdOfPerson1"});
#line 100
 testRunner.When("The person with id come in to the office company \'FLS\'", ((string)(null)), table13, "When ");
#line hidden
#line 103
 testRunner.When("I Get List Of All Company Employers as new Director of company \'FLS\' and put it i" +
                        "n actual scenario context \'allCompanyEmployers\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 104
 testRunner.When("I Get List Of Stuff Office Employers as new Director of company \'FLS\' and put it " +
                        "in expected scenario context \'stuffOfficeEmployers\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 105
 testRunner.Then("I validate count of \'allCompanyEmployers\' collection is \'4\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table14 = new TechTalk.SpecFlow.Table(new string[] {
                            "ID"});
                table14.AddRow(new string[] {
                            "IdOfPerson1"});
                table14.AddRow(new string[] {
                            "IdOfPerson2"});
                table14.AddRow(new string[] {
                            "IdOfPerson3"});
                table14.AddRow(new string[] {
                            "IdOfPerson4"});
#line 106
 testRunner.And("I validate collection of \'allCompanyEmployers\' \'FLS\' company consist of person wi" +
                        "th id", ((string)(null)), table14, "And ");
#line hidden
                TechTalk.SpecFlow.Table table15 = new TechTalk.SpecFlow.Table(new string[] {
                            "ID"});
                table15.AddRow(new string[] {
                            "IdOfPerson1"});
                table15.AddRow(new string[] {
                            "IdOfPerson3"});
                table15.AddRow(new string[] {
                            "IdOfPerson4"});
#line 112
 testRunner.And("I validate collection of \'stuffOfficeEmployers\' \'FLS\' company consist of person w" +
                        "ith id", ((string)(null)), table15, "And ");
#line hidden
#line 117
 testRunner.And("I validate count of \'stuffOfficeEmployers\' collection is \'3\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 118
 testRunner.And("I validate that collection of \'stuffOfficeEmployers\' does not contain absent pers" +
                        "ons", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="GetStuffOfficeEmployers_WhenAllPersonComeOutAndOneComeIn")]
        [Xunit.TraitAttribute("FeatureTitle", "EmployersLibrary")]
        [Xunit.TraitAttribute("Description", "GetStuffOfficeEmployers_WhenAllPersonComeOutAndOneComeIn")]
        [Xunit.TraitAttribute("Category", "Alex")]
        public virtual void GetStuffOfficeEmployers_WhenAllPersonComeOutAndOneComeIn()
        {
            string[] tagsOfScenario = new string[] {
                    "Alex"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("GetStuffOfficeEmployers_WhenAllPersonComeOutAndOneComeIn", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 121
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 3
this.FeatureBackground();
#line hidden
#line 122
 testRunner.When("All person come out from the office company \'FLS\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table16 = new TechTalk.SpecFlow.Table(new string[] {
                            "ID"});
                table16.AddRow(new string[] {
                            "IdOfPerson1"});
#line 123
 testRunner.When("The person with id come in to the office company \'FLS\'", ((string)(null)), table16, "When ");
#line hidden
#line 126
 testRunner.When("I Get List Of All Company Employers as new Director of company \'FLS\' and put it i" +
                        "n actual scenario context \'allCompanyEmployers\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 127
 testRunner.When("I Get List Of Stuff Office Employers as new Director of company \'FLS\' and put it " +
                        "in expected scenario context \'stuffOfficeEmployers\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 128
 testRunner.Then("I validate count of \'allCompanyEmployers\' collection is \'4\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table17 = new TechTalk.SpecFlow.Table(new string[] {
                            "ID"});
                table17.AddRow(new string[] {
                            "IdOfPerson1"});
                table17.AddRow(new string[] {
                            "IdOfPerson2"});
                table17.AddRow(new string[] {
                            "IdOfPerson3"});
                table17.AddRow(new string[] {
                            "IdOfPerson4"});
#line 129
 testRunner.And("I validate collection of \'allCompanyEmployers\' \'FLS\' company consist of person wi" +
                        "th id", ((string)(null)), table17, "And ");
#line hidden
                TechTalk.SpecFlow.Table table18 = new TechTalk.SpecFlow.Table(new string[] {
                            "ID"});
                table18.AddRow(new string[] {
                            "IdOfPerson1"});
#line 135
 testRunner.And("I validate collection of \'stuffOfficeEmployers\' \'FLS\' company consist of person w" +
                        "ith id", ((string)(null)), table18, "And ");
#line hidden
#line 138
 testRunner.And("I validate count of \'stuffOfficeEmployers\' collection is \'1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 139
 testRunner.And("I validate that collection of \'stuffOfficeEmployers\' does not contain absent pers" +
                        "ons", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="GetStuffOfficeEmployers_WhenPersonRemoveFromOffice")]
        [Xunit.TraitAttribute("FeatureTitle", "EmployersLibrary")]
        [Xunit.TraitAttribute("Description", "GetStuffOfficeEmployers_WhenPersonRemoveFromOffice")]
        [Xunit.TraitAttribute("Category", "Alex")]
        public virtual void GetStuffOfficeEmployers_WhenPersonRemoveFromOffice()
        {
            string[] tagsOfScenario = new string[] {
                    "Alex"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("GetStuffOfficeEmployers_WhenPersonRemoveFromOffice", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 142
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 3
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table19 = new TechTalk.SpecFlow.Table(new string[] {
                            "ID"});
                table19.AddRow(new string[] {
                            "IdOfPerson4"});
#line 143
 testRunner.When("The person with id remove from the company \'FLS\'", ((string)(null)), table19, "When ");
#line hidden
#line 146
 testRunner.When("I Get List Of All Company Employers as new Director of company \'FLS\' and put it i" +
                        "n actual scenario context \'allCompanyEmployers\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 147
 testRunner.When("I Get List Of Stuff Office Employers as new Director of company \'FLS\' and put it " +
                        "in expected scenario context \'stuffOfficeEmployers\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 148
 testRunner.Then("I validate count of \'allCompanyEmployers\' collection is \'3\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table20 = new TechTalk.SpecFlow.Table(new string[] {
                            "ID"});
                table20.AddRow(new string[] {
                            "IdOfPerson1"});
                table20.AddRow(new string[] {
                            "IdOfPerson2"});
                table20.AddRow(new string[] {
                            "IdOfPerson3"});
#line 149
 testRunner.And("I validate collection of \'allCompanyEmployers\' \'FLS\' company consist of person wi" +
                        "th id", ((string)(null)), table20, "And ");
#line hidden
                TechTalk.SpecFlow.Table table21 = new TechTalk.SpecFlow.Table(new string[] {
                            "ID"});
                table21.AddRow(new string[] {
                            "IdOfPerson1"});
                table21.AddRow(new string[] {
                            "IdOfPerson2"});
                table21.AddRow(new string[] {
                            "IdOfPerson3"});
#line 154
 testRunner.And("I validate collection of \'stuffOfficeEmployers\' \'FLS\' company consist of person w" +
                        "ith id", ((string)(null)), table21, "And ");
#line hidden
#line 159
 testRunner.And("I validate count of \'stuffOfficeEmployers\' collection is \'3\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 160
 testRunner.And("I validate that collection of \'stuffOfficeEmployers\' does not contain absent pers" +
                        "ons", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="GetStuffOfficeEmployers_WhenAllPersonComeOutAndComeIn")]
        [Xunit.TraitAttribute("FeatureTitle", "EmployersLibrary")]
        [Xunit.TraitAttribute("Description", "GetStuffOfficeEmployers_WhenAllPersonComeOutAndComeIn")]
        [Xunit.TraitAttribute("Category", "Alex")]
        public virtual void GetStuffOfficeEmployers_WhenAllPersonComeOutAndComeIn()
        {
            string[] tagsOfScenario = new string[] {
                    "Alex"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("GetStuffOfficeEmployers_WhenAllPersonComeOutAndComeIn", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 163
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 3
this.FeatureBackground();
#line hidden
#line 164
 testRunner.When("All person come out from the office company \'FLS\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 165
 testRunner.When("All person come in to the office company \'FLS\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 166
 testRunner.When("I Get List Of All Company Employers as new Director of company \'FLS\' and put it i" +
                        "n actual scenario context \'allCompanyEmployers\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 167
 testRunner.When("I Get List Of Stuff Office Employers as new Director of company \'FLS\' and put it " +
                        "in expected scenario context \'stuffOfficeEmployers\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 168
 testRunner.Then("I validate count of \'allCompanyEmployers\' collection is \'4\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table22 = new TechTalk.SpecFlow.Table(new string[] {
                            "ID"});
                table22.AddRow(new string[] {
                            "IdOfPerson1"});
                table22.AddRow(new string[] {
                            "IdOfPerson2"});
                table22.AddRow(new string[] {
                            "IdOfPerson3"});
                table22.AddRow(new string[] {
                            "IdOfPerson4"});
#line 169
 testRunner.And("I validate collection of \'allCompanyEmployers\' \'FLS\' company consist of person wi" +
                        "th id", ((string)(null)), table22, "And ");
#line hidden
                TechTalk.SpecFlow.Table table23 = new TechTalk.SpecFlow.Table(new string[] {
                            "ID"});
                table23.AddRow(new string[] {
                            "IdOfPerson1"});
                table23.AddRow(new string[] {
                            "IdOfPerson2"});
                table23.AddRow(new string[] {
                            "IdOfPerson3"});
                table23.AddRow(new string[] {
                            "IdOfPerson4"});
#line 175
 testRunner.And("I validate collection of \'stuffOfficeEmployers\' \'FLS\' company consist of person w" +
                        "ith id", ((string)(null)), table23, "And ");
#line hidden
#line 181
 testRunner.And("I validate count of \'stuffOfficeEmployers\' collection is \'4\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 182
 testRunner.And("I validate that collection of \'stuffOfficeEmployers\' does not contain absent pers" +
                        "ons", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="GetStuffOfficeEmployers_WhenCompanyIsEmpty")]
        [Xunit.TraitAttribute("FeatureTitle", "EmployersLibrary")]
        [Xunit.TraitAttribute("Description", "GetStuffOfficeEmployers_WhenCompanyIsEmpty")]
        [Xunit.TraitAttribute("Category", "Alex")]
        public virtual void GetStuffOfficeEmployers_WhenCompanyIsEmpty()
        {
            string[] tagsOfScenario = new string[] {
                    "Alex"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("GetStuffOfficeEmployers_WhenCompanyIsEmpty", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 185
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 3
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table24 = new TechTalk.SpecFlow.Table(new string[] {
                            "ID"});
                table24.AddRow(new string[] {
                            "IdOfPerson1"});
                table24.AddRow(new string[] {
                            "IdOfPerson2"});
                table24.AddRow(new string[] {
                            "IdOfPerson3"});
                table24.AddRow(new string[] {
                            "IdOfPerson4"});
#line 186
 testRunner.When("The person with id remove from the company \'FLS\'", ((string)(null)), table24, "When ");
#line hidden
#line 192
 testRunner.When("I Get List Of All Company Employers as new Director of company \'FLS\' and put it i" +
                        "n actual scenario context \'allCompanyEmployers\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 193
 testRunner.When("I Get List Of Stuff Office Employers as new Director of company \'FLS\' and put it " +
                        "in expected scenario context \'stuffOfficeEmployers\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 194
 testRunner.Then("I validate count of \'allCompanyEmployers\' collection is \'0\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 195
 testRunner.And("I validate collection \'allCompanyEmployers\' is empty", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 196
 testRunner.And("I validate collection \'stuffOfficeEmployers\' is empty", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 197
 testRunner.And("I validate count of \'stuffOfficeEmployers\' collection is \'0\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="GetAbsentOfficeEmployers_WhenAllPersonInOffice")]
        [Xunit.TraitAttribute("FeatureTitle", "EmployersLibrary")]
        [Xunit.TraitAttribute("Description", "GetAbsentOfficeEmployers_WhenAllPersonInOffice")]
        [Xunit.TraitAttribute("Category", "Andrew")]
        public virtual void GetAbsentOfficeEmployers_WhenAllPersonInOffice()
        {
            string[] tagsOfScenario = new string[] {
                    "Andrew"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("GetAbsentOfficeEmployers_WhenAllPersonInOffice", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 200
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 3
this.FeatureBackground();
#line hidden
#line 201
 testRunner.When("I Get List Of All Company Employers as new Director of company \'FLS\' and put it i" +
                        "n actual scenario context \'allCompanyEmployers\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 202
 testRunner.When("I Get List Of Absent Office Employers as new Director of company \'FLS\' and put it" +
                        " in expected scenario context \'absentOfficeEmployers\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 203
 testRunner.Then("I validate count of \'allCompanyEmployers\' collection is \'4\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table25 = new TechTalk.SpecFlow.Table(new string[] {
                            "ID"});
                table25.AddRow(new string[] {
                            "IdOfPerson1"});
                table25.AddRow(new string[] {
                            "IdOfPerson2"});
                table25.AddRow(new string[] {
                            "IdOfPerson3"});
                table25.AddRow(new string[] {
                            "IdOfPerson4"});
#line 204
 testRunner.And("I validate collection of \'allCompanyEmployers\' \'FLS\' company consist of person wi" +
                        "th id", ((string)(null)), table25, "And ");
#line hidden
#line 210
 testRunner.And("I validate count of \'absentOfficeEmployers\' collection is \'0\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 211
 testRunner.And("I validate collection \'absentOfficeEmployers\' is empty", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="GetAbsentOfficeEmployers_WhenOnePersonComeOut")]
        [Xunit.TraitAttribute("FeatureTitle", "EmployersLibrary")]
        [Xunit.TraitAttribute("Description", "GetAbsentOfficeEmployers_WhenOnePersonComeOut")]
        [Xunit.TraitAttribute("Category", "Andrew")]
        public virtual void GetAbsentOfficeEmployers_WhenOnePersonComeOut()
        {
            string[] tagsOfScenario = new string[] {
                    "Andrew"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("GetAbsentOfficeEmployers_WhenOnePersonComeOut", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 214
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 3
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table26 = new TechTalk.SpecFlow.Table(new string[] {
                            "ID"});
                table26.AddRow(new string[] {
                            "IdOfPerson4"});
#line 215
 testRunner.When("The person with id come out from the office company \'FLS\'", ((string)(null)), table26, "When ");
#line hidden
#line 218
 testRunner.When("I Get List Of All Company Employers as new Director of company \'FLS\' and put it i" +
                        "n actual scenario context \'allCompanyEmployers\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 219
 testRunner.When("I Get List Of Absent Office Employers as new Director of company \'FLS\' and put it" +
                        " in expected scenario context \'absentOfficeEmployers\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 220
 testRunner.Then("I validate count of \'allCompanyEmployers\' collection is \'4\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table27 = new TechTalk.SpecFlow.Table(new string[] {
                            "ID"});
                table27.AddRow(new string[] {
                            "IdOfPerson1"});
                table27.AddRow(new string[] {
                            "IdOfPerson2"});
                table27.AddRow(new string[] {
                            "IdOfPerson3"});
                table27.AddRow(new string[] {
                            "IdOfPerson4"});
#line 221
 testRunner.And("I validate collection of \'allCompanyEmployers\' \'FLS\' company consist of person wi" +
                        "th id", ((string)(null)), table27, "And ");
#line hidden
#line 227
 testRunner.And("I validate count of \'absentOfficeEmployers\' collection is \'1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table28 = new TechTalk.SpecFlow.Table(new string[] {
                            "ID"});
                table28.AddRow(new string[] {
                            "IdOfPerson4"});
#line 228
 testRunner.And("I validate collection of \'absentOfficeEmployers\' \'FLS\' company consist of person " +
                        "with id", ((string)(null)), table28, "And ");
#line hidden
#line 231
 testRunner.And("I validate that collection of absent office employers \'absentOfficeEmployers\' doe" +
                        "s not contain persons in office", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="GetAbsentOfficeEmployers_WhenAllPersonComeOutAndOneComeIn")]
        [Xunit.TraitAttribute("FeatureTitle", "EmployersLibrary")]
        [Xunit.TraitAttribute("Description", "GetAbsentOfficeEmployers_WhenAllPersonComeOutAndOneComeIn")]
        [Xunit.TraitAttribute("Category", "Andrew")]
        public virtual void GetAbsentOfficeEmployers_WhenAllPersonComeOutAndOneComeIn()
        {
            string[] tagsOfScenario = new string[] {
                    "Andrew"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("GetAbsentOfficeEmployers_WhenAllPersonComeOutAndOneComeIn", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 234
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 3
this.FeatureBackground();
#line hidden
#line 235
 testRunner.When("All person come out from the office company \'FLS\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table29 = new TechTalk.SpecFlow.Table(new string[] {
                            "ID"});
                table29.AddRow(new string[] {
                            "IdOfPerson3"});
#line 236
 testRunner.When("The person with id come in to the office company \'FLS\'", ((string)(null)), table29, "When ");
#line hidden
#line 239
 testRunner.When("I Get List Of All Company Employers as new Director of company \'FLS\' and put it i" +
                        "n actual scenario context \'allCompanyEmployers\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 240
 testRunner.When("I Get List Of Absent Office Employers as new Director of company \'FLS\' and put it" +
                        " in expected scenario context \'absentOfficeEmployers\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 241
 testRunner.Then("I validate count of \'allCompanyEmployers\' collection is \'4\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table30 = new TechTalk.SpecFlow.Table(new string[] {
                            "ID"});
                table30.AddRow(new string[] {
                            "IdOfPerson1"});
                table30.AddRow(new string[] {
                            "IdOfPerson2"});
                table30.AddRow(new string[] {
                            "IdOfPerson3"});
                table30.AddRow(new string[] {
                            "IdOfPerson4"});
#line 242
 testRunner.And("I validate collection of \'allCompanyEmployers\' \'FLS\' company consist of person wi" +
                        "th id", ((string)(null)), table30, "And ");
#line hidden
#line 248
 testRunner.And("I validate count of \'absentOfficeEmployers\' collection is \'3\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table31 = new TechTalk.SpecFlow.Table(new string[] {
                            "ID"});
                table31.AddRow(new string[] {
                            "IdOfPerson1"});
                table31.AddRow(new string[] {
                            "IdOfPerson2"});
                table31.AddRow(new string[] {
                            "IdOfPerson4"});
#line 249
 testRunner.And("I validate collection of \'absentOfficeEmployers\' \'FLS\' company consist of person " +
                        "with id", ((string)(null)), table31, "And ");
#line hidden
#line 254
 testRunner.And("I validate that collection of absent office employers \'absentOfficeEmployers\' doe" +
                        "s not contain persons in office", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="GetAbsentOfficeEmployers_WhenPersonComeOutAndComeInAndComeOut")]
        [Xunit.TraitAttribute("FeatureTitle", "EmployersLibrary")]
        [Xunit.TraitAttribute("Description", "GetAbsentOfficeEmployers_WhenPersonComeOutAndComeInAndComeOut")]
        [Xunit.TraitAttribute("Category", "Andrew")]
        public virtual void GetAbsentOfficeEmployers_WhenPersonComeOutAndComeInAndComeOut()
        {
            string[] tagsOfScenario = new string[] {
                    "Andrew"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("GetAbsentOfficeEmployers_WhenPersonComeOutAndComeInAndComeOut", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 257
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 3
this.FeatureBackground();
#line hidden
#line 258
 testRunner.When("All person come out from the office company \'FLS\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table32 = new TechTalk.SpecFlow.Table(new string[] {
                            "ID"});
                table32.AddRow(new string[] {
                            "IdOfPerson1"});
                table32.AddRow(new string[] {
                            "IdOfPerson2"});
                table32.AddRow(new string[] {
                            "IdOfPerson3"});
#line 259
 testRunner.When("The person with id come in to the office company \'FLS\'", ((string)(null)), table32, "When ");
#line hidden
                TechTalk.SpecFlow.Table table33 = new TechTalk.SpecFlow.Table(new string[] {
                            "ID"});
                table33.AddRow(new string[] {
                            "IdOfPerson1"});
                table33.AddRow(new string[] {
                            "IdOfPerson2"});
                table33.AddRow(new string[] {
                            "IdOfPerson3"});
#line 264
 testRunner.When("The person with id come out from the office company \'FLS\'", ((string)(null)), table33, "When ");
#line hidden
#line 269
 testRunner.When("I Get List Of All Company Employers as new Director of company \'FLS\' and put it i" +
                        "n actual scenario context \'allCompanyEmployers\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 270
 testRunner.When("I Get List Of Absent Office Employers as new Director of company \'FLS\' and put it" +
                        " in expected scenario context \'absentOfficeEmployers\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 271
 testRunner.Then("I validate count of \'allCompanyEmployers\' collection is \'4\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table34 = new TechTalk.SpecFlow.Table(new string[] {
                            "ID"});
                table34.AddRow(new string[] {
                            "IdOfPerson1"});
                table34.AddRow(new string[] {
                            "IdOfPerson2"});
                table34.AddRow(new string[] {
                            "IdOfPerson3"});
                table34.AddRow(new string[] {
                            "IdOfPerson4"});
#line 272
 testRunner.And("I validate collection of \'allCompanyEmployers\' \'FLS\' company consist of person wi" +
                        "th id", ((string)(null)), table34, "And ");
#line hidden
#line 278
 testRunner.And("I validate count of \'absentOfficeEmployers\' collection is \'4\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table35 = new TechTalk.SpecFlow.Table(new string[] {
                            "ID"});
                table35.AddRow(new string[] {
                            "IdOfPerson1"});
                table35.AddRow(new string[] {
                            "IdOfPerson2"});
                table35.AddRow(new string[] {
                            "IdOfPerson3"});
                table35.AddRow(new string[] {
                            "IdOfPerson4"});
#line 279
 testRunner.And("I validate collection of \'absentOfficeEmployers\' \'FLS\' company consist of person " +
                        "with id", ((string)(null)), table35, "And ");
#line hidden
#line 285
 testRunner.And("I validate that collection of absent office employers \'absentOfficeEmployers\' doe" +
                        "s not contain persons in office", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="GetAbsentOfficeEmployers_WhenOnePersonRemoveFromOffice")]
        [Xunit.TraitAttribute("FeatureTitle", "EmployersLibrary")]
        [Xunit.TraitAttribute("Description", "GetAbsentOfficeEmployers_WhenOnePersonRemoveFromOffice")]
        [Xunit.TraitAttribute("Category", "Andrew")]
        public virtual void GetAbsentOfficeEmployers_WhenOnePersonRemoveFromOffice()
        {
            string[] tagsOfScenario = new string[] {
                    "Andrew"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("GetAbsentOfficeEmployers_WhenOnePersonRemoveFromOffice", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 288
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 3
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table36 = new TechTalk.SpecFlow.Table(new string[] {
                            "ID"});
                table36.AddRow(new string[] {
                            "IdOfPerson4"});
#line 289
 testRunner.When("The person with id remove from the company \'FLS\'", ((string)(null)), table36, "When ");
#line hidden
#line 292
 testRunner.When("I Get List Of All Company Employers as new Director of company \'FLS\' and put it i" +
                        "n actual scenario context \'allCompanyEmployers\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 293
 testRunner.When("I Get List Of Absent Office Employers as new Director of company \'FLS\' and put it" +
                        " in expected scenario context \'absentOfficeEmployers\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 294
 testRunner.Then("I validate count of \'allCompanyEmployers\' collection is \'3\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table37 = new TechTalk.SpecFlow.Table(new string[] {
                            "ID"});
                table37.AddRow(new string[] {
                            "IdOfPerson1"});
                table37.AddRow(new string[] {
                            "IdOfPerson2"});
                table37.AddRow(new string[] {
                            "IdOfPerson3"});
#line 295
 testRunner.And("I validate collection of \'allCompanyEmployers\' \'FLS\' company consist of person wi" +
                        "th id", ((string)(null)), table37, "And ");
#line hidden
#line 300
 testRunner.And("I validate count of \'absentOfficeEmployers\' collection is \'0\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 301
 testRunner.And("I validate collection \'absentOfficeEmployers\' is empty", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                EmployersLibraryFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                EmployersLibraryFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
